### ISSUE TITLE
Commuter Pier does not work on workers or artisans

### ISSUE THREAD

**Issue by Anupheaus** [anno-mods/Collection#1]
When I add this mod, it seems to just add the _Pier_ not the _Commuter Pier_.  

If you can explain what needs to be done to fix this I will have a go at fixing it for you and creating an MR.  I'm guessing maybe it is an asset number change or something?  I don't know where the asset numbers come from though, if you can tell me that, I might be able to find out what the new one is and change it to that?  Assuming of course that is the issue.

**Comment by akkzockt** [comment]
Hi, 
Thanks for your report. I transferred it to Collection repository. 

We need to update all Mods in this Collection for the current Anno 1800 Game Update 6.1.

**Comment by akkzockt** [comment]
Update Collection
