### ISSUE TITLE
Several mods outdated

### ISSUE THREAD

**Issue by Marziko** [anno-mods/Collection#11]
Hello, I justed tested out the production boost mods and the reduced farming space mod, both seem to not work after gameupdate 7.

Maybe some ID's changed?

**Comment by akkzockt** [comment]
Hello, that can be, we have to wait until everything is fixed, thanks for your report

**Comment by akkzockt** [comment]
An update for the Collection is planned.  **Soon™**

**Comment by akkzockt** [comment]
**Spice it Up 2.8** update done.

*Todo:* Update other mods and clean up

**Comment by akkzockt** [comment]
Looks like the boost mods are still outdated. I have to remove them in the next time.

**Comment by akkzockt** [comment]
:mega: **Please help us to keep the Collection up-to-date and alive.** 

Report problems here. 

Thanks 
🙏

**Comment by Vivace95** [comment]
Same Marziko, mods like reduce farming space still not working. I tested today and nothing change in value of space e.q potato

**Comment by akkzockt** [comment]
Thanks for testing. I think it's about time to remove the boost mods. Sad. 😢

**Comment by Vivace95** [comment]
Or time to fix it somehow :P

**Comment by Vivace95** [comment]
https://www.youtube.com/watch?v=_ei088csFwY&t=116s this guy use reduce farming space, and his lestplay look working with this mod. Meybe we try to ask him, what he have in their folders (like code or something) @akkzockt

**Comment by akkzockt** [comment]
good suggestion, but you don't know exactly when he made the let's plays and if there are any problems with the mods at the moment. i have no contact to him. can you ask him a short question about it? in the comments it says that he had the mods from nexus, i will check if there is an update there.

**Comment by Vivace95** [comment]
Ye, I wrote a message to him, now wait for an answer. Maybe you'll find something on nexus in the meantime.

**Comment by Vivace95** [comment]
Hell yeah. @akkzockt i find a solution for Boosting mining,production and space. I use this mod for more testing (https://www.nexusmods.com/anno1800/mods/6) and install Anno Mod Manager (https://www.nexusmods.com/anno1800/mods/35) after tracking Anno files in this program and lauching game from this its finally mod work and reduce space (screen for proof https://ibb.co/ZLc5DNX - sorry for polish fonts, hehe)

**Comment by akkzockt** [comment]
It's now up-to-date. Thanks for your help @Vivace95 🥇 

Lets close this and open new issues when mods become outdated.
