### ISSUE TITLE
 Townhall, Tradeunion, Harbor Office increased Influenceradius

### ISSUE THREAD

**Issue by jimmyblackwolf** [anno-mods/Collection#16]
Townhall, Tradeunion, Harbor Office increased Influenceradius not working in new update

**Comment by ItBurnsWhenIP-2020** [comment]
Influence radius seems to be working for me, however it seems being to add more than 3 item slots does not work now. In earlier patches i could just edit the assets file to increase radius and item slots. Any body else experiencing the same?

**Comment by jimmyblackwolf** [comment]
Socket count cant work i just changed it but never works

**Comment by ItBurnsWhenIP-2020** [comment]
Yeah it worked fine in previous versions but the new 7.1 patch seems have
broke it.

**Comment by jimmyblackwolf** [comment]
Plz fix it

**Comment by ItBurnsWhenIP-2020** [comment]
Wish I could I'm just a user of the mod..... Let's hope the author will see
the posts

**Comment by jimmyblackwolf** [comment]
No just me

**Comment by akkzockt** [comment]
I forwarded it but it cannot be fixed. Sorry
