### ISSUE TITLE
[Adjustments] Map Seeds Patch 1 + 2 needs update to work

### ISSUE THREAD

**Issue by jimmyblackwolf** [anno-mods/Collection#24]
[Adjustments] Map Seeds Patch 1 + 2 needs update to work

**Comment by akkzockt** [comment]
There is no **Map Seeds Patch 1 + 2** in the Collection, just **Map Seeds Patch 3** -> [here](https://github.com/anno-mods/Collection/tree/master/%5BAdjustments%5D%20Map%20Seeds%20Patch%203)
