### ISSUE TITLE
Game Crash after ingame playtime of 12:30 houres

### ISSUE THREAD

**Issue by Pankraz01** [anno-mods/Collection#32]
Game Crashes after connecting commuter pier with road network in new world.

Opponent already has a pier in new world and it works fine.
If another player sets the pier and connecting it, the game crashes instantly

game crashes for all players

if you want to destroy or move the pier, it will also crash the game

**Comment by Pankraz01** [comment]
game crashed for all players

**Comment by Pankraz01** [comment]
@akkzockt this is not the real cause of this bug. I think the game crashes after a ceartain amount of time played

**Comment by akkzockt** [comment]
Alright, I forwarded it.

**Comment by akkzockt** [comment]
And if it's not the cause, maybe we should describe the issue another way, right? 🤔

**Comment by Pankraz01** [comment]
Okay I tested something:

There is an ingame time mark, if you pass this (12,30 hours playtime) the game stops working. We loaded different savegames (30 mins, 1 hour, 2 houres before) and still got the crash at 12,30 houres playtime. We can assume that we did not do the same things in after in the different savegames.
Without Mods, the game works fine. 

Now im Trying to load only the Spiced It Up Mods from their original site and watch what will happened

**Comment by Pankraz01** [comment]
Fishboss updated the assets.xml and fixed it. It is the Hotels Mod

**Comment by lsalazarm99** [comment]
What version do you mean it was fixed? I see the version mod of this repo is 2.0.3 from July, and Nexus version is 2.0.6 (published Aug 26, one day after your last reply). 2.0.4 and 2.0.6 fixed some bugs and added some compatibility issues with other mods.

I guess this fix is not in master, isn't it? So I should update manually. Should I do a PR?

**Comment by akkzockt** [comment]
Thanks for the hint. Yes, unfortunately I did not update all mods in this Collection lately. 

If you want to do a PR on it, you are welcome. Otherwise I will update them again when I find the time.

**Comment by Pankraz01** [comment]
@akkzockt 

Like I said, Fishboss updated the XML File for a fix. I can do a request later

**Comment by Pankraz01** [comment]
@akkzockt is the XML File Up To Date or should still I push the fixed version?

**Comment by lsalazarm99** [comment]
At the time the issue was opened again, I tried with the latest update of the Hotels mod but it didn't work either. I had to remove it.

**Comment by akkzockt** [comment]
Just in time, I did it just for you! 😉 

https://github.com/anno-mods/Fishboss-Mods
