### ISSUE TITLE
All mods have disappeared

### ISSUE THREAD

**Issue by akkzockt** [anno-mods/Collection#40]
If you download directly from GitHub, it will abort at ~1GB. 

Cloning is still possible. 

We need to take a look and maybe think of a new way...

**Comment by akkzockt** [comment]
One way could be, like with [Spice it Up](https://github.com/anno-mods/Spice-it-Up), to move some mods to other repositories...

**Comment by Anthonyjohn77** [comment]
still not working

**Comment by akkzockt** [comment]
yeah

**Comment by akkzockt** [comment]
Because the download doesn't work anymore (it won't work in the old Manager) -> we have to CHANGE IT. No Panic 🔨

**Comment by akkzockt** [comment]
## (Old) Collection Forks

- https://github.com/anno-mods/Collection/network/members
- Check [Network](https://github.com/anno-mods/Collection/network) for latest changes

**Comment by akkzockt** [comment]
### It is time. The old Mod Manager has passed away. Funeral flowers and candles are welcome.

Please use the new **AMM** now. It is really great! RIP. Spread the word!

- https://www.nexusmods.com/anno1800/mods/35
- https://github.com/LemonDrop1228/anno1800-mod-manager

**Comment by Nathan1852** [comment]
How would I get the config which mods where activated with the old mod loader? I started a game a few hours ago, scanned for mods just now after playing for a bit and all mods are gone

**Comment by Pankraz01** [comment]
Download for me works fine. Maybe we should .zip the Repository, so other people can download just the zip-File via the Release-Function of GitHub

**Comment by akkzockt** [comment]
The reason that the download is now working again is probably that the old Mods are no longer in this Collection. 
As backup you can use the **Forks** (see link above). 

@Pankraz01 The idea with the 'Release'-Function is interesting. Visitors of GitHub can download a repository by simply clicking 'Download ZIP' (under 'Code'). Maybe this is too hidden for many people. 
Or Collections can put a download link into **README**. 

Otherwise, the new Manager should decide how to access Collections. I can also imagine cloning the repositories. 
Which could also have many advantages.

As you all may have noticed, I have changed Collection to a **Template**. This should make it easier to set up new Collections.
