### ISSUE TITLE
Gas Heaters not affected by influence bonus (and probably also not by trade union)

### ISSUE THREAD

**Issue by daish0** [anno-mods/Collection#6]
Just found that quirk while testing a few mods from the Spice-It-Up 2.7 collection.

**Comment by akkzockt** [comment]
Thanks for your report, i forwarded it. What kind of influence bonus would that be?

**Comment by akkzockt** [comment]
Can you check this with latest Collection / Spice it Up ??

**Comment by akkzockt** [comment]
Should be fixed. Please report if still something is missing. Thanks
