### ISSUE TITLE
Oil Depot is missing it's icon

### ISSUE THREAD

**Issue by daish0** [anno-mods/Collection#7]
The icon is specified in the .xml as:
data/graphics/hc/__icons/oil_pier.png
but it doesn't come with the mod package.

I created an altered pier icon (red to black) for the oil depot here: https://imgur.com/a/cXLeFeA
You just have to add that to a folder as specified in the xml and it just works (hope imgur doesn't destroy the transparency of the png).
I don't know issues with copyright and those images though ... (took it from the anno 1800 wiki)

**Comment by akkzockt** [comment]
Thanks for your report, i forwarded it.

**Comment by akkzockt** [comment]
Can you check this with latest Collection / Spice it Up ??

**Comment by akkzockt** [comment]
Should be fixed. Please report if still something is missing. Thanks
