### ISSUE TITLE
Feature Request: Reusable and shareable blueprints

### ISSUE THREAD

**Issue by J7mbo** [anno-mods/Collection#8]
Hi! Thanks for the lib and great work so far!

I think a lot of people would be interested in re-using and sharing blueprints. I haven't looked at the Python API yet, but would something like this be possible:

- On keyboard shortcut, gather state of currently 'pipette-selected' items -- position, location etc
- Throw this off to some backend I can build and host
- Provide a command to retrieve this state from the backend

Possible? Thoughts?

**Comment by akkzockt** [comment]
Looks like a real challange, right? 😉

**Comment by J7mbo** [comment]
After discussing, turns out it's not only a real challenge but not possible given current APIs. :( It would have to be a 'manual hack' with image recognition. I'll close this ticket as it looks like something that can't be done in this repo.
